apiVersion: v1
kind: Namespace
metadata:
  name: lynnsanitygg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynnsanitygg-frontend
  namespace: lynnsanitygg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynnsanitygg
  template:
    metadata:
      labels:
        app: lynnsanitygg
    spec:
      containers:
        - name: lynnsanitygg-frontend
          image: lynnsanity/lynnsanity.gg:1.2.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lynnsanitygg-frontend-svc
  namespace: lynnsanitygg
spec:
  type: ClusterIP
  selector:
    app: lynnsanitygg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
