---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynnsanity-website
  namespace: lynnsanityio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynnsanity-website
  template:
    metadata:
      labels:
        app: lynnsanity-website
    spec:
      containers:
        - name: lynnsanity-website
          image: lynnsanity/lynnsanity.io:1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lynnsanity-website-service
  namespace: lynnsanityio
spec:
  selector:
    app: lynnsanity-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: lynnsanity-website-ingress
#  namespace: lynnsanityio
#spec:
#  rules:
#    - host: lynnsanity.io
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: lynnsanity-website-service
#                port:
#                  number: 80
